prompts:
  - |
    You are a helpful AI assistant. Solve this step by step:
    Problem: {{problem}}
    Please show your work and provide the final answer clearly.

providers:
  - id: "openrouter:openai/gpt-4.1-nano"
    config:
      apiKey: "your_openai_api_key"
      max_tokens: 8192

tests:
  - vars:
      problem: A store sells apples for $2 per pound and oranges for $3 per pound. If someone buys 4 pounds of apples and 2 pounds of oranges, and pays with a $20 bill, how much change should they receive?
    assert:
      - type: contains
        value: "$6"
        weight: 2
        metric: correct_calculation
